<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.view_response_listener' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/EventListener/ViewResponseListener.php';

return $this->privates['fos_rest.view_response_listener'] = new \FOS\RestBundle\EventListener\ViewResponseListener(($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')), false);
