<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nXdCzWT' shared service.

return $this->privates['.service_locator.nXdCzWT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'place' => ['privates', '.errored..service_locator.nXdCzWT.App\\Entity\\Place', NULL, 'Cannot autowire service ".service_locator.nXdCzWT": it references class "App\\Entity\\Place" but no such service exists.'],
], [
    'place' => 'App\\Entity\\Place',
]);
