<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.78dnRMb' shared service.

return $this->privates['.service_locator.78dnRMb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PlaceController::getPlaceAction' => ['privates', '.service_locator.nXdCzWT', 'get_ServiceLocator_NXdCzWTService.php', true],
    'App\\Controller\\PlaceController:getPlaceAction' => ['privates', '.service_locator.nXdCzWT', 'get_ServiceLocator_NXdCzWTService.php', true],
], [
    'App\\Controller\\PlaceController::getPlaceAction' => '?',
    'App\\Controller\\PlaceController:getPlaceAction' => '?',
]);
