<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.decoder.json' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Decoder/DecoderInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Decoder/JsonDecoder.php';

return $this->privates['fos_rest.decoder.json'] = new \FOS\RestBundle\Decoder\JsonDecoder();
