<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGUG1uxP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGUG1uxP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGUG1uxP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGUG1uxP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGUG1uxP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GUG1uxP',
    'container.build_id' => '7f3d4651',
    'container.build_time' => 1573062835,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGUG1uxP');
